# Generated by Django 5.1.1 on 2024-10-26 05:57

import cloudinary.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenDanhMuc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PhieuMuon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayMuon', models.DateField(default=django.utils.timezone.now)),
                ('ngayTraDuKien', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietPhieuMuon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayTraThucTe', models.DateField(blank=True, null=True)),
                ('tinhTrang', models.CharField(choices=[('borrowed', 'Đang mượn'), ('returned', 'Đã trả'), ('late', 'Trễ hạn')], default='borrowed', max_length=10)),
                ('tienPhat', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('ghiChu', models.TextField(blank=True, null=True)),
                ('phieuMuon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_phieu_muon', to='ThuVien.phieumuon')),
            ],
        ),
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenSach', models.CharField(max_length=255)),
                ('tenTacGia', models.CharField(max_length=255)),
                ('nXB', models.CharField(max_length=255)),
                ('namXB', models.IntegerField()),
                ('soLuong', models.IntegerField()),
                ('soSachDangMuon', models.IntegerField(default=0)),
                ('anhSach', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='anhSach')),
                ('totalBorrowCount', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('danhMuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='ThuVien.danhmuc')),
            ],
        ),
        migrations.AddField(
            model_name='phieumuon',
            name='sach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phieu_muon', to='ThuVien.sach'),
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar')),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('nam_sinh', models.IntegerField(blank=True, null=True)),
                ('chucVu', models.CharField(choices=[('nhan_vien', 'Nhân viên'), ('doc_gia', 'Độc giả')], default='doc_gia', max_length=255)),
                ('soLuongMuon', models.IntegerField(default=0)),
                ('soLuongTra', models.IntegerField(default=0)),
                ('soLuongQuaHan', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='phieumuon',
            name='docGia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChiaSe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('sach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThuVien.sach')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=255)),
                ('sach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThuVien.sach')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thich', models.CharField(default='like', max_length=10)),
                ('sach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThuVien.sach')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'sach')},
            },
        ),
    ]
